services:
  eureka-server:
    image: openjdk:17.0.1
    container_name: eureka-server
    working_dir: /app
    volumes:
      - ./eureka-server/build/libs:/app
    command: ["java", "-jar", "/app/eureka-server-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8761:8761"
    env_file:
      - .env.docker
    networks:
      - ofl-net

  gateway:
    image: openjdk:17.0.1
    container_name: gateway
    working_dir: /app
    volumes:
      - ./gateway-service/build/libs:/app
    command: ["java", "-jar", "/app/gateway-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - eureka-server
    networks:
      - ofl-net

  user-service:
    image: openjdk:17.0.1
    container_name: user-service
    working_dir: /app
    volumes:
      - ./user-service/build/libs:/app
    command: ["java", "-jar", "/app/user-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - postgres
    env_file:
      - .env.docker
    networks:
      - ofl-net

  hub-service:
    image: openjdk:17.0.1
    container_name: hub-service
    working_dir: /app
    volumes:
      - ./hub-service/build/libs:/app
    command: ["java", "-jar", "/app/hub-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8200:8200"
    depends_on:
      - eureka-server
      - postgres
      - redis
    env_file:
      - .env.docker
    networks:
      - ofl-net

  order-service:
    image: openjdk:17.0.1
    container_name: order-service
    working_dir: /app
    volumes:
      - ./order-service/build/libs:/app
    command: ["java", "-jar", "/app/order-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8400:8400"
    depends_on:
      - eureka-server
      - postgres
    env_file:
      - .env.docker
    networks:
      - ofl-net

  notification-service:
    image: openjdk:17.0.1
    container_name: notification-service
    working_dir: /app
    volumes:
      - ./notification-service/build/libs:/app
    command: ["java", "-jar", "/app/notification-service-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8700:8700"
    depends_on:
      - eureka-server
      - postgres
    env_file:
      - .env.docker
    networks:
      - ofl-net

  postgres:
    image: postgres:17
    container_name: postgres-ofl
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    networks:
      - ofl-net

  redis:
    image: redis:7
    container_name: redis-ofl
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ofl-net

networks:
  ofl-net:

volumes:
  postgres_data:
  redis_data:
